### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by Alipoodle** [GreenTurtwig/osu-info#1]
The Application need an Icon!

**Comment by GreenTurtwig** [comment]
Err... I guess you can submit issues here? :-P
Your kinda helping anyway. :-)

**Comment by Alipoodle** [comment]
![osuwithouttext](https://cloud.githubusercontent.com/assets/17199186/14827535/c94a55be-0bda-11e6-80e9-e4f8f87093b7.png)
Icon sofar

**Comment by GreenTurtwig** [comment]
But, but, I finished it. :-(

**Comment by Alipoodle** [comment]
Icon Created and Added to program. Release 1.1.0

**Comment by GreenTurtwig** [comment]
:-)
