### ISSUE TITLE
Hitting Enter to Search.

### ISSUE THREAD

**Issue by Alipoodle** [GreenTurtwig/osu-info#2]
Within VB you can check when a specific Key is pressed within the Textbox, this could look for when the enter key is hit and then run the same code as the Search button. Although this may be better to implement once the problem of the wrong name being put it.

**Comment by Alipoodle** [comment]
```
Private Sub Txt_PlayerName_KeyPress(sender As Object, e As KeyPressEventArgs) Handles Txt_PlayerName.KeyPress
        If e.KeyChar = "Enter" Then
            'Code Goes HERE :D
        End If
    End Sub
```

**Comment by Alipoodle** [comment]
Done and uploaded

**Comment by GreenTurtwig** [comment]
:-)
