### ISSUE TITLE
Unhandled exception - Index was out of range

### ISSUE THREAD

**Issue by dintendocoltd** [GreenTurtwig/osu-info#5]
Error Log: http://paste.ubuntu.com/16086145/

Screenshot:
<img src="https://dintendocoltd.co.uk/image/src18-48-19.png"></img>

**Comment by GreenTurtwig** [comment]
Looks like it's crashing for me too if a user doesn't have five top scores. It will crash when it starts looking for one, but there isn't. Should be able to fix in a 1.1.2 release. :-)

**Comment by Alipoodle** [comment]
Might also want to test it if a person only have 1-4 Top plays...

**Comment by Alipoodle** [comment]
Crashes when user has 4 or less Plays.
Tester Username: Pikam
Only has 1 "top" play

Error Message:
![image](https://cloud.githubusercontent.com/assets/17199186/14867064/9f1c5276-0cbe-11e6-81db-f9a0a44aee7c.png)

**Comment by GreenTurtwig** [comment]
Yeah that's what I said :-P

**Comment by Alipoodle** [comment]
Fixed Version 1.1.2
