### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by dintendocoltd** [GreenTurtwig/osu-info#8]
Todo: Setup GitHub pages and port over the html files that I have written :smile:

**Comment by GreenTurtwig** [comment]
I'll make a new repo :cat:

**Comment by GreenTurtwig** [comment]
https://github.com/GreenTurtwig/osu-info-Web

**Comment by GreenTurtwig** [comment]
http://greenturtwig.github.io/osu-info-Web/
