### ISSUE TITLE
Bug when using the rainbow 'Easter egg'

### ISSUE THREAD

**Issue by dintendocoltd** [GreenTurtwig/osu-info#9]
Video: https://dintendocoltd.co.uk/vid/osuinfobug.mp4

So, I tried out the 'Easter egg' that Rowan and Alex put together and it worked (as expected), however, this 'feature' did not turn off when I tried to change the colour theme or when I entered another osu! username apart from GreenTurtwig and Alipoodle.

:egg:

**Comment by dintendocoltd** [comment]
My server really does like decompressing video files :unamused:

**Comment by Alipoodle** [comment]
Rowan intended they you didn't keep it on until you reboot!

**Comment by GreenTurtwig** [comment]
Actually that's not intended, I was just lazy :-P  
Those usernames only working is however intended. :cat:

**Comment by GreenTurtwig** [comment]
@alipoodle FYI you still haven't submitted the pull request :-P

**Comment by Alipoodle** [comment]
Sorry what was that "just lazy"

**Comment by GreenTurtwig** [comment]
Yep ;-)
Making an app "Random Kats" is way more fun at the moment. :-)

**Comment by dintendocoltd** [comment]
Any updates on this?

**Comment by dintendocoltd** [comment]
Any updates on this?

**Comment by GreenTurtwig** [comment]
I've decided to doesn't really need fixing, since it is an easter egg after all and not an ACTUAL feature. 😺
